export const COMMANDS =  {

}

export const TOOLBAR_ITEMS = {
    SEPARATOR : 'SEPARATOR',
    FONT_SELECT : 'FONT_SELECT',
    FONTSIZE_SELECT : 'FONTSIZE_SELECT',
    BOLD : 'BOLD',
    ITALIC : 'ITALIC',
    UNDERLINE : 'UNDERLINE',
    FONTCOLOR_SELECT : 'FONTCOLOR_SELECT',
    BACKGROUNDCOLOR_SELECT : 'BACKGROUNDCOLOR_SELECT',
    ALIGN_LEFT : 'ALIGN_LEFT',
    ALIGN_CENTER : 'ALIGN_CENTER',
    ALIGN_RIGHT : 'ALIGN_RIGHT',
    LIST_ORDERED : 'LIST_ORDERED',
    LIST_UNORDERED : 'LIST_UNORDERED',
    INDENT : 'INDENT',
    OUTDENT : 'OUTDENT',
    LINE_HEIGHT_SELECT : 'LINE_HEIGHT_SELECT',
    SYMBOL_SELECT : 'SYMBOL_SELECT',
    HR : 'HR',
    LINK : 'LINK',
    TABLE_SELECT : 'TABLE_SELECT',
    IMAGE_SELECT : 'IMAGE_SELECT',
    OPEN_WORD : 'OPEN_WORD'
}